"""Generate the two fonts of Dark Island 1 from the artwork in `font_art.py`.

    py -3 tools/generate_font.py

Writes `src/font_8x8.asm` and `src/font_4x8.asm`, both tables of the characters
32 to 127, and the sheet `gfx/fonts.png` to look at them with.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from PIL import Image

import zx
from font_art import FONT_4X8, FONT_8X8

ROOT = Path(__file__).resolve().parents[1]
FONT_8X8_PATH = ROOT / "src" / "font_8x8.asm"
FONT_4X8_PATH = ROOT / "src" / "font_4x8.asm"
PREVIEW_PATH = ROOT / "gfx" / "fonts.png"

FIRST_CHAR = 32
LAST_CHAR = 127

SAMPLE = [
    "DARK ISLAND 1",
    "THE ROTTEN PIER",
    "ABCDEFGHIJKLM",
    "NOPQRSTUVWXYZ",
    "abcdefghijklm",
    "nopqrstuvwxyz",
    "0123456789 !?.,:-'()",
]

SMALL_SAMPLE = [
    "THE SAWMILL UNDER THE HILL",
    "TAKE THE GAS MASK - THE AIR BURNS",
    "LIVES 3   ENERGY 10   TOOLS 0/8",
]


def table_8x8():
    """Eight bytes for every character, from the space to the last one."""
    rows = []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        char = chr(code)
        art = FONT_8X8.get(char)
        data = zx.glyph_bytes(art) if art else bytes(8)
        rows.append((code, char, data))
    return rows


def table_4x8():
    """Eight bytes for every character, the pixels in the high half of the byte."""
    rows = []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        char = chr(code)
        art = FONT_4X8.get(char)
        data = zx.glyph_bytes(art, width=4) if art else bytes(8)
        rows.append((code, char, data))
    return rows


def name_of(char: str) -> str:
    return {" ": "space", '"': "quote", "\\": "backslash"}.get(char, char)


def source(label: str, header: str, rows) -> str:
    out = [header, "", label + ":"]
    for code, char, data in rows:
        out.append("        ; {} - {}".format(code, name_of(char)))
        out.append(
            "        defb  " + ", ".join("{:3d}".format(value) for value in data)
        )
    out.append("")
    return "\n".join(out)


HEADER_8X8 = """;###############################################################################
;##### The gothic font of Dark Island 1. Eight by eight, one character for ######
;##### every code from 32 to 127. It is written by the same hand as the #########
;##### blackletter logo in the panel: heavy stems, bars instead of serifs #######
;##### and no round corner anywhere. ###########################################
;##### #########################################################################
;##### GENERATED by tools/generate_font.py - do not edit it here. ###############
;###############################################################################"""

HEADER_4X8 = """;###############################################################################
;##### The small font of the panel. Three pixels wide and five high, so two #####
;##### characters fit in one character of the screen and a whole sentence #######
;##### fits in one row. The lower case letters are the capitals again. ##########
;##### #########################################################################
;##### GENERATED by tools/generate_font.py - do not edit it here. ###############
;###############################################################################"""


def preview() -> Image.Image:
    """A sheet with both fonts, the way they will look on the screen."""
    scale = 3
    margin = 8
    line_height = 16
    width = 32 * 8
    height = margin * 2 + line_height * len(SAMPLE) + 8 + 8 * len(SMALL_SAMPLE)
    height = (height + 7) // 8 * 8

    canvas = zx.Canvas(width, height, strict=False)
    y = margin
    inks = [
        (zx.YELLOW, True),
        (zx.WHITE, True),
        (zx.CYAN, True),
        (zx.CYAN, True),
        (zx.WHITE, False),
        (zx.WHITE, False),
        (zx.GREEN, True),
    ]
    for index, text in enumerate(SAMPLE):
        ink, bright = inks[index % len(inks)]
        canvas.text(FONT_8X8, text, margin, y, ink=ink, bright=bright, advance=8)
        y += line_height
    y += 4
    for text in SMALL_SAMPLE:
        canvas.text(FONT_4X8, text, margin, y, ink=zx.YELLOW, bright=True, advance=4)
        y += 8
    return canvas.preview(scale=scale)


def main() -> None:
    zx.write_source(FONT_8X8_PATH, source("Font8x8", HEADER_8X8, table_8x8()))
    zx.write_source(FONT_4X8_PATH, source("Font4x8", HEADER_4X8, table_4x8()))
    zx.write_preview(PREVIEW_PATH, preview())


if __name__ == "__main__":
    main()
