;###############################################################################
;##### The picture of the game's panel: the blackletter logo of the game, the ###
;##### island under the moon and the two labels. The panel is 32x5 characters ###
;##### and every character of it is one tile; tile 0 is the empty one and is #####
;##### not stored. The places of the skulls, of the energy and of the room's ####
;##### description are empty here, the game draws them by itself. ##############
;##### #########################################################################
;##### GENERATED by tools/generate_panel.py - do not edit it here. #############
;###############################################################################

PanelTiles:
        ; Tile 1
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00011111
        defb  %01111111
        defb  %01111001
        defb  %01111000
        defb  %01111000
        ; Tile 2
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %11110000
        defb  %11111000
        defb  %11111100
        defb  %11111110
        defb  %01111111
        ; Tile 3
        defb  %00000000
        defb  %00000001
        defb  %00000001
        defb  %00000000
        defb  %00000001
        defb  %00000001
        defb  %00000001
        defb  %00000011
        ; Tile 4
        defb  %00000000
        defb  %11110000
        defb  %11100000
        defb  %11100000
        defb  %11110000
        defb  %11110000
        defb  %11111000
        defb  %11111000
        ; Tile 5
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000011
        defb  %00001111
        defb  %00001111
        defb  %00001111
        defb  %00001111
        ; Tile 6
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %11111110
        defb  %11111111
        defb  %00111111
        defb  %00011111
        defb  %00001111
        ; Tile 7
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000011
        defb  %00001111
        defb  %10001111
        defb  %10001111
        defb  %00001111
        ; Tile 8
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000001
        defb  %00000011
        defb  %00000110
        defb  %00001110
        defb  %00011100
        ; Tile 9
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %10000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 10
        defb  %00000000
        defb  %00111111
        defb  %01111110
        defb  %00001110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        ; Tile 11
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000011
        defb  %00001111
        defb  %00011110
        defb  %00111110
        defb  %00111111
        ; Tile 12
        defb  %00000000
        defb  %00111100
        defb  %01111101
        defb  %11111000
        defb  %11111100
        defb  %01111100
        defb  %01111000
        defb  %00100000
        ; Tile 13
        defb  %00000000
        defb  %11111100
        defb  %11111000
        defb  %00110000
        defb  %11110000
        defb  %11110000
        defb  %11110000
        defb  %11110000
        ; Tile 14
        defb  %00000000
        defb  %00011111
        defb  %00011110
        defb  %00001110
        defb  %00011111
        defb  %00011111
        defb  %00011111
        defb  %00111111
        ; Tile 15
        defb  %00000000
        defb  %00000000
        defb  %00000001
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %10000000
        defb  %10000000
        ; Tile 16
        defb  %00000000
        defb  %11111000
        defb  %11111000
        defb  %00110000
        defb  %11110000
        defb  %11110000
        defb  %11111000
        defb  %11111100
        ; Tile 17
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00011100
        defb  %01111100
        defb  %01111100
        defb  %01111100
        defb  %01111100
        ; Tile 18
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00111111
        defb  %11111111
        defb  %11110011
        defb  %11110001
        defb  %11110000
        ; Tile 19
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %11100000
        defb  %11110000
        defb  %11111000
        defb  %11111100
        defb  %11111110
        ; Tile 20
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000001
        defb  %00000011
        ; Tile 21
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00111000
        defb  %01111000
        defb  %11111000
        defb  %11111000
        defb  %01111000
        ; Tile 22
        defb  %00000011
        defb  %00001110
        defb  %00011100
        defb  %00011100
        defb  %00111000
        defb  %00111000
        defb  %00111000
        defb  %00111100
        ; Tile 23
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00011001
        defb  %00001101
        defb  %00000111
        defb  %00000011
        ; Tile 24
        defb  %00000000
        defb  %00000110
        defb  %00000110
        defb  %00000111
        defb  %10000011
        defb  %11000011
        defb  %11100011
        defb  %11110001
        ; Tile 25
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %01100000
        defb  %11000000
        defb  %10000000
        defb  %10000001
        defb  %11000111
        ; Tile 26
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00110000
        defb  %01110011
        defb  %11100110
        defb  %11111100
        defb  %10010000
        ; Tile 27
        defb  %01111000
        defb  %01111000
        defb  %01111110
        defb  %01111100
        defb  %01111000
        defb  %11111000
        defb  %11111000
        defb  %01111000
        ; Tile 28
        defb  %00111111
        defb  %00011111
        defb  %00011111
        defb  %00011111
        defb  %00011111
        defb  %00011111
        defb  %00011111
        defb  %00011111
        ; Tile 29
        defb  %00000011
        defb  %00000011
        defb  %00000111
        defb  %00000111
        defb  %00000110
        defb  %00001110
        defb  %00001111
        defb  %00011111
        ; Tile 30
        defb  %11111000
        defb  %11111100
        defb  %01111100
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %11111111
        defb  %11111111
        ; Tile 31
        defb  %00001111
        defb  %00001111
        defb  %00001111
        defb  %00001111
        defb  %00001111
        defb  %00001111
        defb  %00001111
        defb  %00001111
        ; Tile 32
        defb  %00001111
        defb  %00001110
        defb  %00011110
        defb  %00011100
        defb  %11111100
        defb  %11111100
        defb  %01111100
        defb  %01111110
        ; Tile 33
        defb  %00111000
        defb  %01110000
        defb  %11100000
        defb  %11100000
        defb  %11100000
        defb  %11110000
        defb  %11111000
        defb  %11111100
        ; Tile 34
        defb  %00111110
        defb  %00111110
        defb  %00111111
        defb  %00111110
        defb  %00111110
        defb  %01111110
        defb  %01111110
        defb  %00111110
        ; Tile 35
        defb  %00011111
        defb  %00011111
        defb  %00001111
        defb  %00000011
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 36
        defb  %10000000
        defb  %10000000
        defb  %11100000
        defb  %11111000
        defb  %11111000
        defb  %11111101
        defb  %01111101
        defb  %01111100
        ; Tile 37
        defb  %11110000
        defb  %11110000
        defb  %11111100
        defb  %11111000
        defb  %11110000
        defb  %11110000
        defb  %11110000
        defb  %11110000
        ; Tile 38
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000001
        ; Tile 39
        defb  %00111111
        defb  %00111111
        defb  %01110111
        defb  %01110011
        defb  %01100011
        defb  %11100011
        defb  %11111111
        defb  %11111111
        ; Tile 40
        defb  %10000000
        defb  %11000000
        defb  %11000000
        defb  %11100000
        defb  %11100000
        defb  %11100000
        defb  %11110000
        defb  %11110000
        ; Tile 41
        defb  %11111100
        defb  %11111110
        defb  %11111111
        defb  %11111111
        defb  %11111111
        defb  %11110111
        defb  %11110011
        defb  %11110001
        ; Tile 42
        defb  %01111100
        defb  %01111100
        defb  %01111100
        defb  %01111100
        defb  %11111100
        defb  %11111101
        defb  %11111101
        defb  %11111100
        ; Tile 43
        defb  %01111110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        ; Tile 44
        defb  %00000010
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 45
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %01111000
        ; Tile 46
        defb  %00111100
        defb  %00011110
        defb  %00011111
        defb  %00001111
        defb  %00000011
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 47
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %11000000
        defb  %11000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 48
        defb  %00111000
        defb  %00011110
        defb  %00001111
        defb  %00000111
        defb  %00000011
        defb  %00000001
        defb  %00000001
        defb  %00000000
        ; Tile 49
        defb  %11101111
        defb  %11111110
        defb  %11111100
        defb  %11110000
        defb  %11100000
        defb  %11100000
        defb  %11100000
        defb  %11100000
        ; Tile 50
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %01111111
        defb  %01111111
        defb  %00000000
        defb  %00000000
        ; Tile 51
        defb  %00011110
        defb  %00011100
        defb  %00111000
        defb  %01110000
        defb  %11100000
        defb  %10000000
        defb  %00000000
        defb  %00000000
        ; Tile 52
        defb  %00011100
        defb  %00011100
        defb  %00111000
        defb  %00111000
        defb  %00111000
        defb  %01100000
        defb  %00000000
        defb  %00000000
        ; Tile 53
        defb  %00001111
        defb  %00001111
        defb  %00001111
        defb  %00000111
        defb  %00000111
        defb  %00000011
        defb  %00000000
        defb  %00000000
        ; Tile 54
        defb  %10001111
        defb  %10011111
        defb  %11001111
        defb  %11001111
        defb  %11001111
        defb  %00001100
        defb  %00000000
        defb  %00000000
        ; Tile 55
        defb  %00111111
        defb  %10111111
        defb  %00011111
        defb  %00001111
        defb  %00001111
        defb  %00000110
        defb  %00000000
        defb  %00000000
        ; Tile 56
        defb  %00011111
        defb  %00001111
        defb  %10001111
        defb  %10001111
        defb  %11001111
        defb  %00001100
        defb  %00000000
        defb  %00000000
        ; Tile 57
        defb  %11111110
        defb  %01111111
        defb  %00111111
        defb  %00011111
        defb  %00001111
        defb  %00000110
        defb  %00000000
        defb  %00000000
        ; Tile 58
        defb  %00000000
        defb  %00000000
        defb  %10000000
        defb  %10000000
        defb  %11000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 59
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %00111110
        defb  %00110000
        defb  %00111111
        defb  %01111110
        ; Tile 60
        defb  %00000000
        defb  %00011100
        defb  %01111110
        defb  %00111110
        defb  %00111111
        defb  %00011111
        defb  %00000000
        defb  %00000000
        ; Tile 61
        defb  %00111000
        defb  %01111000
        defb  %01110000
        defb  %11110000
        defb  %11110000
        defb  %10000000
        defb  %00000000
        defb  %00000000
        ; Tile 62
        defb  %11110000
        defb  %11110000
        defb  %11110000
        defb  %11110000
        defb  %11111111
        defb  %11111111
        defb  %00000000
        defb  %00000000
        ; Tile 63
        defb  %00000001
        defb  %00000001
        defb  %00000011
        defb  %00000011
        defb  %11110011
        defb  %10000110
        defb  %00000000
        defb  %00000000
        ; Tile 64
        defb  %11000000
        defb  %11000000
        defb  %10000000
        defb  %10000000
        defb  %10000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 65
        defb  %11111000
        defb  %11111000
        defb  %11111100
        defb  %01111100
        defb  %01111100
        defb  %00110000
        defb  %00000000
        defb  %00000000
        ; Tile 66
        defb  %11110001
        defb  %11110000
        defb  %11110000
        defb  %11110000
        defb  %11110000
        defb  %11000000
        defb  %00000000
        defb  %00000000
        ; Tile 67
        defb  %11111100
        defb  %11111100
        defb  %01111100
        defb  %01111100
        defb  %01111100
        defb  %01100000
        defb  %01111100
        defb  %11111100
        ; Tile 68
        defb  %00111100
        defb  %00111000
        defb  %01110000
        defb  %11100000
        defb  %11000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 69
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000011
        defb  %00000000
        defb  %00000000
        ; Tile 70
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %01111000
        defb  %11111111
        defb  %11111100
        defb  %00000000
        defb  %00000000
        ; Tile 71
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %10000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 72
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000001
        defb  %00000110
        ; Tile 73
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00001100
        defb  %00011111
        defb  %10000011
        defb  %00011110
        ; Tile 74
        defb  %00000000
        defb  %00000000
        defb  %00110011
        defb  %01111111
        defb  %11111111
        defb  %11000001
        defb  %11111111
        defb  %00001111
        ; Tile 75
        defb  %00000011
        defb  %11001111
        defb  %11111111
        defb  %11111111
        defb  %10001111
        defb  %11111111
        defb  %11111111
        defb  %11100001
        ; Tile 76
        defb  %11110000
        defb  %11111110
        defb  %11111111
        defb  %11111111
        defb  %11111110
        defb  %11111111
        defb  %00000111
        defb  %11111111
        ; Tile 77
        defb  %00000000
        defb  %00110000
        defb  %11111100
        defb  %11111111
        defb  %00011111
        defb  %11111100
        defb  %11000001
        defb  %11111111
        ; Tile 78
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %11000000
        defb  %00110000
        defb  %11111100
        defb  %11111110
        ; Tile 79
        defb  %00000000
        defb  %00100011
        defb  %00100001
        defb  %00100001
        defb  %00100001
        defb  %00111011
        defb  %00000000
        defb  %00000000
        ; Tile 80
        defb  %00000000
        defb  %10101011
        defb  %00101010
        defb  %00101011
        defb  %00101010
        defb  %10010011
        defb  %00000000
        defb  %00000000
        ; Tile 81
        defb  %00000000
        defb  %10011000
        defb  %00100000
        defb  %00010000
        defb  %00001000
        defb  %10110000
        defb  %00000000
        defb  %00000000
        ; Tile 82
        defb  %00000000
        defb  %11101010
        defb  %10001100
        defb  %11001110
        defb  %10000110
        defb  %11101010
        defb  %00000000
        defb  %00000000
        ; Tile 83
        defb  %00000000
        defb  %11101100
        defb  %10001010
        defb  %11001100
        defb  %10001010
        defb  %11101010
        defb  %00000000
        defb  %00000000
        ; Tile 84
        defb  %00000000
        defb  %01101010
        defb  %10001010
        defb  %10100100
        defb  %10100100
        defb  %01100100
        defb  %00000000
        defb  %00000000
        ; Tile 85
        defb  %00010000
        defb  %11101100
        defb  %00000011
        defb  %00000000
        defb  %01001111
        defb  %10111000
        defb  %00000100
        defb  %00000011
        ; Tile 86
        defb  %00000010
        defb  %00000001
        defb  %11010000
        defb  %11101100
        defb  %00000111
        defb  %00111011
        defb  %11100000
        defb  %00011000
        ; Tile 87
        defb  %00000000
        defb  %11000001
        defb  %00111110
        defb  %00001101
        defb  %00000000
        defb  %00000000
        defb  %11111110
        defb  %00110001
        ; Tile 88
        defb  %00000000
        defb  %11000000
        defb  %00000011
        defb  %11000001
        defb  %00111110
        defb  %01110000
        defb  %00001111
        defb  %10000100
        ; Tile 89
        defb  %00000100
        defb  %00011011
        defb  %11100000
        defb  %00001000
        defb  %00001111
        defb  %01110000
        defb  %10000000
        defb  %00110000
        ; Tile 90
        defb  %00000000
        defb  %10000011
        defb  %01000100
        defb  %00011011
        defb  %11100001
        defb  %00000110
        defb  %01111000
        defb  %01100100
        ; Tile 91
        defb  %11000000
        defb  %00110000
        defb  %00001111
        defb  %00000011
        defb  %00001100
        defb  %11100000
        defb  %00011011
        defb  %00001100
        ; Tile 92
        defb  %00001000
        defb  %01000111
        defb  %11000000
        defb  %00110000
        defb  %00111111
        defb  %01001100
        defb  %10000011
        defb  %01100000
        ; Tile 93
        defb  %00111100
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 94
        defb  %00000100
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 95
        defb  %01111000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 96
        defb  %00001111
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 97
        defb  %10000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 98
        defb  %00110000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        ; Tile 99
        defb  %00011100
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000
        defb  %00000000

; Number of the tile for every character of the panel.
PanelMap:
        defb    0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,   0,  14,  15,  16,  17,  18,  19,  20,  21,   0,  22,   0,   0,  23,  24,  25,  26,   0
        defb    0,  27,  28,  29,  30,  31,  32,  31,  33,   0,  34,  35,  36,  37,  38,  39,  40,  41,  42,  37,  43,  44,  45,   0,  46,  47,   0,   0,  48,  49,   0,   0
        defb    0,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  62,  68,  69,  70,  71,   0,  72,  73,  74,  75,  76,  77,  78
        defb   79,  80,  81,   0,   0,   0,   0,   0,   0,   0,  82,  83,  84,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  85,  86,  87,  88,  89,  90,  91,  92
        defb    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  93,  94,   0,  95,  96,  97,  98,  99

; Color of every character of the panel.
PanelAttributes:
        defb    7,  70,  70,  70,  70,  70,  70,  70,  70,  70,  70,  70,  70,  70,   7,  70,  70,  70,  70,  70,  70,  70,  70,   7,  70,   7,   7,  71,  71,  71,  71,   7
        defb    7,  70,  70,  70,  70,  70,  70,  70,  70,   7,  70,  70,  70,  70,  70,  70,  70,  70,  70,  70,  70,  70,  70,   7,  70,  70,   7,   7,  71,  71,   7,   7
        defb    7,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   6,   7,  71,  71,  71,  71,  71,  71,  71
        defb    7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,  69,  69,  69,  69,  69,  69,  69,  69
        defb   69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69

;-------------------------------------------------------------------------------
; The graphics the game draws into the panel: the skulls of the lives in
; the three moments of their gnashing, and one cell of the energy bar.

; The skull of one life, at rest.
SpriteDataSkull:
        defb  %00111000
        defb  %01111100
        defb  %10010010
        defb  %10010010
        defb  %11010110
        defb  %01111100
        defb  %01010100
        defb  %00000000

; A spark of light in its eyes.
SpriteDataSkullGlint:
        defb  %00111000
        defb  %01111100
        defb  %10010010
        defb  %11010110
        defb  %11010110
        defb  %01111100
        defb  %01010100
        defb  %00000000

; Its jaw drops for a moment.
SpriteDataSkullChatter:
        defb  %00111000
        defb  %01111100
        defb  %10010010
        defb  %10010010
        defb  %11010110
        defb  %01111100
        defb  %01111100
        defb  %00111000

; One point of the energy the player has.
GfxEnergyFull:
        defb  %00000000
        defb  %00011000
        defb  %00111100
        defb  %01111110
        defb  %00111100
        defb  %00011000
        defb  %00000000
        defb  %00000000

; One point the player has already spent.
GfxEnergyEmpty:
        defb  %00000000
        defb  %00011000
        defb  %00100100
        defb  %01000010
        defb  %00100100
        defb  %00011000
        defb  %00000000
        defb  %00000000
