;###############################################################################
;##### The sprites the rooms of Dark Island 1 are built from. Every sprite is ###
;##### the width in characters and the height in pixel lines, then the bitmap ###
;##### by pixel lines, and after it one attribute for every character. ##########
;##### #########################################################################
;##### GENERATED by tools/generate_sprites.py - do not edit it here. ############
;###############################################################################

;-------------------------------------------------------------------------------
; The ground of the island; five of these fill the game field.
SpriteGround:
        defb    6, 8

SpriteDataGround:
        defb  255, 255, 255, 255, 255, 255
        defb  255, 255, 255, 255, 255, 255
        defb  107, 255, 107, 107, 255, 107
        defb  255, 255, 255, 255, 255, 255
        defb  181, 181, 255, 181, 181, 255
        defb  255, 255, 255, 255, 255, 255
        defb  255, 206, 206, 255, 206, 206
        defb  251, 251, 255, 251, 251, 255

SpriteAttributesGround:
        defb    7,   7,   7,   7,   7,   7

;-------------------------------------------------------------------------------
; A short piece of the ground, for the ledges.
SpriteGroundSmall:
        defb    2, 8

SpriteDataGroundSmall:
        defb  255, 255
        defb  255, 255
        defb  107, 255
        defb  255, 255
        defb  181, 181
        defb  255, 255
        defb  255, 206
        defb  251, 251

SpriteAttributesGroundSmall:
        defb    7,   7

;-------------------------------------------------------------------------------
; A tuft of the hard grass that grows on the rock.
SpriteGrass:
        defb    1, 8

SpriteDataGrass:
        defb    0
        defb   16
        defb  146
        defb  150
        defb  186
        defb  219
        defb  123
        defb   24

SpriteAttributesGrass:
        defb   68

;-------------------------------------------------------------------------------
; A boulder, two characters wide.
SpriteRock:
        defb    2, 16

SpriteDataRock:
        defb    0,   0
        defb    7, 224
        defb   31, 248
        defb   59, 252
        defb  127, 255
        defb  123, 239
        defb  255, 255
        defb  239, 251
        defb  255, 255
        defb  123, 239
        defb   63, 252
        defb   31, 248
        defb    0,   0
        defb    0,   0
        defb    0,   0
        defb    0,   0

SpriteAttributesRock:
        defb    7,   7
        defb    7,   7

;-------------------------------------------------------------------------------
; The ladder between the levels of the island.
SpriteLadder:
        defb    2, 24

SpriteDataLadder:
        defb  192,  12
        defb  192,  12
        defb  255, 255
        defb  255, 255
        defb  192,  12
        defb  192,  12
        defb  192,  12
        defb  192,  12
        defb  255, 255
        defb  255, 255
        defb  192,  12
        defb  192,  12
        defb  192,  12
        defb  192,  12
        defb  255, 255
        defb  255, 255
        defb  192,  12
        defb  192,  12
        defb  192,  12
        defb  192,  12
        defb  255, 255
        defb  255, 255
        defb  192,  12
        defb  192,  12

SpriteAttributesLadder:
        defb   70,  70
        defb   70,  70
        defb   70,  70

;-------------------------------------------------------------------------------
; A low cloud - on this island it always carries rain.
SpriteCloud:
        defb    3, 16

SpriteDataCloud:
        defb    3, 252,   0
        defb   15, 255,   0
        defb   63, 255, 192
        defb  127, 255, 240
        defb  127, 255, 252
        defb  255, 255, 255
        defb  127, 255, 254
        defb   31, 255, 248
        defb    0,   0,   0
        defb    0,   0,   0
        defb    0,   0,   0
        defb    0,   0,   0
        defb    0,   0,   0
        defb    0,   0,   0
        defb    0,   0,   0
        defb    0,   0,   0

SpriteAttributesCloud:
        defb   71,  71,  71
        defb   71,  71,  71

;-------------------------------------------------------------------------------
; A wooden crate, the kind the tools are packed in.
SpriteCrate:
        defb    2, 16

SpriteDataCrate:
        defb  255, 255
        defb  128,   1
        defb  176,  13
        defb  140,  49
        defb  131, 193
        defb  131, 193
        defb  140,  49
        defb  176,  13
        defb  128,   1
        defb  128,   1
        defb  176,  13
        defb  140,  49
        defb  131, 193
        defb  131, 193
        defb  140,  49
        defb  255, 255

SpriteAttributesCrate:
        defb    6,   6
        defb    6,   6

;-------------------------------------------------------------------------------
; A dead tree, four characters wide and three high.
SpriteDeadTree:
        defb    4, 24

SpriteDataDeadTree:
        defb    0,   0,   0,   0
        defb    1, 152, 192,   0
        defb    1, 249, 192,   0
        defb    0, 127,   0,  12
        defb  192,  30,   1, 220
        defb  192,  12,   3, 248
        defb  110,  14,   7, 240
        defb   63,  14,  31, 224
        defb   63, 135, 190,   0
        defb    7, 199, 252,   0
        defb    3, 231, 240,   0
        defb    1, 247, 224,   0
        defb    0, 127, 192,   0
        defb    0,  63, 128,   0
        defb    0,  31, 128,   0
        defb    0,  15,   0,   0
        defb    0,  15,   0,   0
        defb    0,  15,   0,   0
        defb    0,  15,   0,   0
        defb    0,  15, 128,   0
        defb    0,   7, 128,   0
        defb    0,  15, 192,   0
        defb    0, 127, 248,   0
        defb    0, 127, 248,   0

SpriteAttributesDeadTree:
        defb    7,   7,   7,   7
        defb    7,   7,   7,   7
        defb    7,   7,   7,   7

;-------------------------------------------------------------------------------
; The names the rooms call the sprites by.
SPRITE_GROUND                   equ SpriteGround
SPRITE_GROUND_SMALL             equ SpriteGroundSmall
SPRITE_GRASS                    equ SpriteGrass
SPRITE_ROCK                     equ SpriteRock
SPRITE_LADDER                   equ SpriteLadder
SPRITE_CLOUD                    equ SpriteCloud
SPRITE_CRATE                    equ SpriteCrate
SPRITE_DEAD_TREE                equ SpriteDeadTree
